<a href="https://colab.research.google.com/github/adebisijoy/Python-in-Machine-Learning/blob/main/Graded_Quiz_Tag_along_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns

df = pd.read_csv(r"/content/sample_data/energydata_complete.csv")
df.head()

date  Appliances  lights     T1       RH_1    T2       RH_2  \
0  2016-01-11 17:00:00          60      30  19.89  47.596667  19.2  44.790000   
1  2016-01-11 17:10:00          60      30  19.89  46.693333  19.2  44.722500   
2  2016-01-11 17:20:00          50      30  19.89  46.300000  19.2  44.626667   
3  2016-01-11 17:30:00          50      40  19.89  46.066667  19.2  44.590000   
4  2016-01-11 17:40:00          60      40  19.89  46.333333  19.2  44.530000   

      T3       RH_3         T4  ...         T9   RH_9     T_out  Press_mm_hg  \
0  19.79  44.730000  19.000000  ...  17.033333  45.53  6.600000        733.5   
1  19.79  44.790000  19.000000  ...  17.066667  45.56  6.483333        733.6   
2  19.79  44.933333  18.926667  ...  17.000000  45.50  6.366667        733.7   
3  19.79  45.000000  18.890000  ...  17.000000  45.40  6.250000        733.8   
4  19.79  45.000000  18.890000  ...  17.000000  45.40  6.133333        733.9   

   RH_out  Windspeed  Visibility  Tdewpoint        rv1        rv2  
0    92.0   7.000000   63.000000        5.3  13.275433  13.275433  
1    92.0   6.666667   59.166667        5.2  18.606195  18.606195  
2    92.0   6.333333   55.333333        5.1  28.642668  28.642668  
3    92.0   6.000000   51.500000        5.0  45.410389  45.410389  
4    92.0   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 29 columns]

T1, Temperature in Kitcken area in celsius
RH_1, Humidity in kitchen area, in %
T2, Temperature in living room area, in celsius
RH_2 Humidity in Living room area, in %
T3, Temperature in laundry room area

RH_3, Humidity in laundry room area, in %

T4, Temperature in office room, in Celsius

RH_4, Humidity in office room, in %

T5, Temperature in bathroom, in Celsius

RH_5, Humidity in bathroom, in %

T6, Temperature outside the building (north side), in Celsius

RH_6, Humidity outside the building (north side), in %

T7, Temperature in ironing room , in Celsius

RH_7, Humidity in ironing room, in %

T8, Temperature in teenager room 2, in Celsius

RH_8, Humidity in teenager room 2, in %

T9, Temperature in parents room, in Celsius

In [116]:
x = df['T2']
y = df['T6']

In [117]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 1)

In [125]:
x_train = np.array(x_train).reshape(-1, 1)
y_train = np.array(y_train).reshape(-1, 1)
x_test = np.array(x_test).reshape(-1, 1)
y_test = np.array(y_test).reshape(-1, 1)

In [126]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
# fit the model to the training dataset
model.fit(x_train, y_train)
# obtain predictions
predicted_values = (model.predict(x_test))
predicted_values

array([[ 3.36810969],
       [ 9.26944595],
       [14.4817373 ],
       ...,
       [ 6.05760757],
       [ 9.46578671],
       [ 7.39124288]])

In [127]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, predicted_values))
round(rmse, 3)

3.612

In [128]:
x = df.drop(['date', 'lights'], axis = 1)
y = df['Appliances']

In [141]:
y = np.array(y).reshape(-1, 1)

In [139]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_scaler = scaler.fit_transform(x)
x_scaler

array([[0.04672897, 0.32734952, 0.56618659, ..., 0.53846154, 0.26544891,
        0.26544891],
       [0.04672897, 0.32734952, 0.54132648, ..., 0.53393665, 0.37208289,
        0.37208289],
       [0.03738318, 0.32734952, 0.53050179, ..., 0.52941176, 0.57284766,
        0.57284766],
       ...,
       [0.24299065, 0.91974657, 0.53866618, ..., 0.89894419, 0.58397859,
        0.58397859],
       [0.38317757, 0.91974657, 0.54949087, ..., 0.8974359 , 0.12637146,
        0.12637146],
       [0.39252336, 0.91974657, 0.53875791, ..., 0.8959276 , 0.68239057,
        0.68239057]])

In [142]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_scaler = scaler.fit_transform(y)
x_scaler

array([[0.04672897],
       [0.04672897],
       [0.03738318],
       ...,
       [0.24299065],
       [0.38317757],
       [0.39252336]])

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_scaler, y, test_size = 0.3, random_state = 42)

In [144]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso()
lasso_reg.fit(x_train, y_train)

Lasso()

In [145]:
model = lasso_reg.predict(x_test)
model

array([ 45.82719612,  90.7800529 ,  54.81776748, ...,  54.81776748,
       108.76119561,  54.81776748])

In [150]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(x_train, y_train)
round(mae, 3)

97.646

In [151]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(x_train, y_train))
round(rmse, 3)

141.827

In [153]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, model)
round(mae, 3)

6.105

In [155]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, model))
round(rmse, 3)

10.246