<a href="https://colab.research.google.com/github/adebisijoy/Python-in-Machine-Learning/blob/main/Introduction_to_Python_for_machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Getting Started with Python and Data Analysis**

Data Science Pipeline: Data scoping, Data review, Feature Engineering, Feature review, model selection and review, model evaluation and insights, interaction and production.
Data science is not a linear process but an iterative process.

**NumPy Array and Vectorization**

Vectorisation in numpy arrays allows for faster processing by eliminating for loops when dealing with arrays of equal shape. Similarly, scalars are also propagated element-wise across an array. For arrays with different sizes, it is impossible to perform element-wise operations instead; numpy handles this by broadcasting provided the dimensions of the arrays are the same or, one of the dimensions of the array is 1.

In [43]:
# Covention for importing Numpy
import numpy as np

arr = [6, 7, 8, 9, 10]
print(type(arr))

<class 'list'>


In [3]:
a = np.array(arr)
print(type(a))
print(a.shape)
print(a.ndim)

<class 'numpy.ndarray'>
(5,)
1


In [9]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
print(b.ndim)
b.shape

2


(2, 3)

In [12]:
# Inbuilt functions that can be used to initialize numpy
np.random.random((2,3))

array([[0.806222  , 0.96899663, 0.33929059],
       [0.83314422, 0.90666065, 0.63870708]])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# Intra-operability of arrays and scalers
c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])
d = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])

In [20]:
c + d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [21]:
c * d

array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [22]:
5 / d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [24]:
c ** 2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

In [30]:
a[0]

6

In [29]:
# Indexing With Arrays & Using Arrays for Data Processing
a[3]

9

In [31]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
b[0, 0]

1

In [33]:
b[1, 2]

6

In [34]:
c[0,1]

8.0

In [35]:
d[1, 0:2]

array([9., 8.])

In [36]:
e = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18], [19, 20, 21]])
e

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [38]:
e[:3, :2]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [39]:
# interger indexing
e[[2, 0, 3, 1], [2, 1, 0, 2]]

array([18, 11, 19, 15])

In [42]:
# Boolean indexing meeting a specified condition
e[e > 15]

array([16, 17, 18, 19, 20, 21])

In [ ]:
b

In [ ]:
b

In [ ]:
b